### PR TITLE
update docker

### PR DESCRIPTION
**Pull request by Resonance1584**

### CODE REVIEW

**Comment by matt-in-a-hat** [comment]
What's `apt`?

**Comment by Resonance1584** [comment]
@matt-in-a-hat no idea but I think its a docker dependency - updated docker as it would no longer install with the older version

**Comment by WayneKoorts** [comment]
apt is the debian package manager, also used by Ubuntu.  Similar to rpm.

**Comment by matt-in-a-hat** [comment]
Ah cool. Cheers Wayno :grin: 

Looks good Lewis :+1:

**Pull request merged**
