### PR TITLE
Add puppetlabs/postgresql module with postgis

### PR DESCRIPTION
**Pull request by matt-in-a-hat**
@digitalsadhu it was giving me many errors to do with `docker` and `apt`, does something need updating? I'm guessing it automatically updated the apt module, as it made changes to the modules/apt folder that I didn't commit.

### CODE REVIEW

**Comment by digitalsadhu** [comment]
Odd. Afraid I have no idea. Is it working despite the errors?

**Comment by matt-in-a-hat** [comment]
The rest of the box seems fine... do we even use any docker stuff?

**Comment by digitalsadhu** [comment]
I don't think so.

**Comment by markstuart** [comment]
I notice that the error messages are all to do with redirection from http to https:
`==> default: Error: Could not set 'present' on ensure: redirection forbidden: http://get.docker.io/gpg -> https://get.docker.io/gpg at 93:/tmp/vagrant-puppet-3/modules-0/apt/manifests/key.pp`
so it's probably just a matter of using the correct url for Docker?

**Pull request merged**
