### PR TITLE
Fix the way user is granted db privileges

### PR DESCRIPTION
**Pull request by digitalsadhu**
Previous method was not changing to use the
postgres user before running the grant

### CODE REVIEW

**Comment by digitalsadhu** [comment]
@markstuart @matt-in-a-hat @Resonance1584 @anotheredward @pnw @boredsteve 
Can I get a what whaaat?

**Comment by markstuart** [comment]
Nice, yeah that was pretty annoying. I had to `sudo -u postgres` or something like that from memory

**Comment by markstuart** [comment]
Oh and also: 'what whaaat!'

**Comment by digitalsadhu** [comment]
niiice... can I get a "thumbs uuuuup"?

**Comment by markstuart** [comment]
:+1:  :shipit: :racehorse: :rainbow: :rabbit2: :mega: :tm:

**Comment by Resonance1584** [comment]
:dog2:

**Pull request merged**
